export const timezones = [
    { value: 'Pacific/Midway', label: '國際換日線西 (UTC-11)' },
    { value: 'Pacific/Honolulu', label: '夏威夷 (UTC-10)' },
    { value: 'America/Anchorage', label: '阿拉斯加 (UTC-9)' },
    { value: 'America/Los_Angeles', label: '洛杉磯 (PST, UTC-8)' },
    { value: 'America/Denver', label: '丹佛 (MST, UTC-7)' },
    { value: 'America/Chicago', label: '芝加哥 (CST, UTC-6)' },
    { value: 'America/New_York', label: '紐約 (EST, UTC-5)' },
    { value: 'America/Caracas', label: '加拉加斯 (UTC-4)' },
    { value: 'America/Sao_Paulo', label: '聖保羅 (UTC-3)' },
    { value: 'Atlantic/South_Georgia', label: '南喬治亞 (UTC-2)' },
    { value: 'Atlantic/Azores', label: '亞速群島 (UTC-1)' },
    { value: 'Europe/London', label: '倫敦 (GMT, UTC+0)' },
    { value: 'Europe/Paris', label: '巴黎 (CET, UTC+1)' },
    { value: 'Europe/Helsinki', label: '赫爾辛基 (EET, UTC+2)' },
    { value: 'Europe/Moscow', label: '莫斯科 (MSK, UTC+3)' },
    { value: 'Asia/Dubai', label: '杜拜 (UTC+4)' },
    { value: 'Asia/Karachi', label: '喀拉蚩 (UTC+5)' },
    { value: 'Asia/Dhaka', label: '達卡 (UTC+6)' },
    { value: 'Asia/Bangkok', label: '曼谷 (UTC+7)' },
    { value: 'Asia/Taipei', label: '台灣 (CST, UTC+8)' },
    { value: 'Asia/Tokyo', label: '東京 (JST, UTC+9)' },
    { value: 'Australia/Sydney', label: '雪梨 (AEST, UTC+10)' },
    { value: 'Pacific/Guadalcanal', label: '索羅門群島 (UTC+11)' },
    { value: 'Pacific/Auckland', label: '奧克蘭 (NZST, UTC+12)' },
];
